### ISSUE TITLE
Using Graph mode and bytes file

### ISSUE THREAD

**Issue by kevinren1108** [xstreck1/flAppy-bIrd#1]
I want to know how can I use graph mode and bytes files to see the train result. My unity version is 2018.3.10f1. I didn't see any option to use graph mode in flappybrain entity.

**Comment by xstreck1** [comment]
Hi, the .bytes file produced by the training process is a TensorFlow model, that can be restored from python (https://www.tensorflow.org/guide/saved_model) and then visualized in TensorBoard (https://www.tensorflow.org/guide/graph_viz). However I've done that and the network is exceedingly complex and it was not very informative to me.
